### ISSUE TITLE
Cluster can scale down but not back up

### ISSUE THREAD

**Issue by adbreind** [coiled/cloud-issues#16]
Given a default cluster with 4 workers, I can do:
`cluster.scale(2)` 
and it scales down to 2 workers but if I then run
`cluster.scale(4)` 
no additional workers are allocated.

This may be by design, in which case I'd create a feature request to:

*Allow scaling up/down below a quota limit*

**Comment by mrocklin** [comment]
It takes about a minute for things to scale up.  You may want to couple
scale with client.wait_for_workers(4)

**Comment by adbreind** [comment]
Success: Tested with additional wait time and with `wait_for_workers`
Thanks!
