### ISSUE TITLE
Cluster creation failures

### ISSUE THREAD

**Issue by cicdw** [coiled/cloud-issues#23]
I recently started playing with Coiled and spent more time than I'd like to admit trying to debug my failed cluster startup.  

I created a few software environments and then used:
```python
from coiled import CoiledCluster

cluster = CoiledCluster(configuration="cicdw/my-test-env")
```
which produced a massive Django traceback; at the top I found:
```
{"type": "websocket.close", "extra": "Cluster configuration not found"}
```

Turns out I still need to create a _cluster_ configuration as well (which makes sense now that I realize it).  

Two points of feedback from this:
- cleaner error messages would be nice (I imagine the Django traceback is for devs right now)
- make the names of the coiled configs more explicit, e.g., `coiled/default-env` and `coiled/default-cluster`

**Comment by mrocklin** [comment]
Given how common this is we might consider checking for an equivalent SoftwareEnvironment, and sending back a verbose/informative error message that encourages the user to create a cluster configuration

```python
ValueError(
    "Cluster configuration cicdw/my-test-env not found."
    "However, we did notice that there is a Software environment cicdw/my-test-env"
    "Maybe you wanted to make a cluster configuration with this software environment\n\n"
    "  coiled.create_cluster_configuration(name='cicdw/my-test-env', software='cicdw/my-test-env')"
)

If it's easier we might do this logic on the Python client side too.
