### ISSUE TITLE
Nodejs needs to be added to Dask Jupyter Extension Install Docs

### ISSUE THREAD

**Issue by mmccarty** [coiled/cloud-issues#25]
```
conda install -c conda-forge dask-labextension
```
Should be...
```
conda install -c conda-forge dask-labextension nodejs
```

Otherwise, you get an error when you register the JupyterLab extension.

**Comment by mrocklin** [comment]
Thanks for raising this @mmccarty .  We will probably resolve this tomorrow.

We should also include nb_conda.  I wonder if we want to change this section from examples/dask-labextension to a full blown "Here is how we recommend installing JupyterLab and why" page.

cc @jrbourbeau

**Comment by jrbourbeau** [comment]
Thanks for bringing this up @mmccarty! (Also nice to see you here : ) )

>  I wonder if we want to change this section from examples/dask-labextension to a full blown "Here is how we recommend installing JupyterLab and why" page

+1 I started making a new "JupyterLab" page this afternoon that does this. Will finish it up tomorrow

**Comment by jrbourbeau** [comment]
Here's the new JupyterLab page https://coiled.io/cloud/user_guide/jupyter.html (with updated installation instructions for `dask-labextension`)
